// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: proto/numbers.proto

package numbers

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NumbersClient is the client API for Numbers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NumbersClient interface {
	GetRandom(ctx context.Context, in *GetRandomRequest, opts ...grpc.CallOption) (*GetRandomReply, error)
}

type numbersClient struct {
	cc grpc.ClientConnInterface
}

func NewNumbersClient(cc grpc.ClientConnInterface) NumbersClient {
	return &numbersClient{cc}
}

func (c *numbersClient) GetRandom(ctx context.Context, in *GetRandomRequest, opts ...grpc.CallOption) (*GetRandomReply, error) {
	out := new(GetRandomReply)
	err := c.cc.Invoke(ctx, "/numbers.Numbers/GetRandom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NumbersServer is the server API for Numbers service.
// All implementations must embed UnimplementedNumbersServer
// for forward compatibility
type NumbersServer interface {
	GetRandom(context.Context, *GetRandomRequest) (*GetRandomReply, error)
	mustEmbedUnimplementedNumbersServer()
}

// UnimplementedNumbersServer must be embedded to have forward compatible implementations.
type UnimplementedNumbersServer struct {
}

func (UnimplementedNumbersServer) GetRandom(context.Context, *GetRandomRequest) (*GetRandomReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandom not implemented")
}
func (UnimplementedNumbersServer) mustEmbedUnimplementedNumbersServer() {}

// UnsafeNumbersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NumbersServer will
// result in compilation errors.
type UnsafeNumbersServer interface {
	mustEmbedUnimplementedNumbersServer()
}

func RegisterNumbersServer(s grpc.ServiceRegistrar, srv NumbersServer) {
	s.RegisterService(&Numbers_ServiceDesc, srv)
}

func _Numbers_GetRandom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NumbersServer).GetRandom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/numbers.Numbers/GetRandom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NumbersServer).GetRandom(ctx, req.(*GetRandomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Numbers_ServiceDesc is the grpc.ServiceDesc for Numbers service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Numbers_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "numbers.Numbers",
	HandlerType: (*NumbersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandom",
			Handler:    _Numbers_GetRandom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/numbers.proto",
}
