// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: proto/numbers.proto

package numbers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRandomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Highest int32 `protobuf:"varint,1,opt,name=highest,proto3" json:"highest,omitempty"`
}

func (x *GetRandomRequest) Reset() {
	*x = GetRandomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_numbers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomRequest) ProtoMessage() {}

func (x *GetRandomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_numbers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomRequest.ProtoReflect.Descriptor instead.
func (*GetRandomRequest) Descriptor() ([]byte, []int) {
	return file_proto_numbers_proto_rawDescGZIP(), []int{0}
}

func (x *GetRandomRequest) GetHighest() int32 {
	if x != nil {
		return x.Highest
	}
	return 0
}

type GetRandomReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GetRandomReply) Reset() {
	*x = GetRandomReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_numbers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRandomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRandomReply) ProtoMessage() {}

func (x *GetRandomReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_numbers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRandomReply.ProtoReflect.Descriptor instead.
func (*GetRandomReply) Descriptor() ([]byte, []int) {
	return file_proto_numbers_proto_rawDescGZIP(), []int{1}
}

func (x *GetRandomReply) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_numbers_proto protoreflect.FileDescriptor

var file_proto_numbers_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x22, 0x2c,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x22, 0x28, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x4c, 0x0a, 0x07, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x12, 0x41, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x12, 0x19,
	0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_numbers_proto_rawDescOnce sync.Once
	file_proto_numbers_proto_rawDescData = file_proto_numbers_proto_rawDesc
)

func file_proto_numbers_proto_rawDescGZIP() []byte {
	file_proto_numbers_proto_rawDescOnce.Do(func() {
		file_proto_numbers_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_numbers_proto_rawDescData)
	})
	return file_proto_numbers_proto_rawDescData
}

var file_proto_numbers_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_numbers_proto_goTypes = []interface{}{
	(*GetRandomRequest)(nil), // 0: numbers.GetRandomRequest
	(*GetRandomReply)(nil),   // 1: numbers.GetRandomReply
}
var file_proto_numbers_proto_depIdxs = []int32{
	0, // 0: numbers.Numbers.GetRandom:input_type -> numbers.GetRandomRequest
	1, // 1: numbers.Numbers.GetRandom:output_type -> numbers.GetRandomReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_numbers_proto_init() }
func file_proto_numbers_proto_init() {
	if File_proto_numbers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_numbers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRandomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_numbers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRandomReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_numbers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_numbers_proto_goTypes,
		DependencyIndexes: file_proto_numbers_proto_depIdxs,
		MessageInfos:      file_proto_numbers_proto_msgTypes,
	}.Build()
	File_proto_numbers_proto = out.File
	file_proto_numbers_proto_rawDesc = nil
	file_proto_numbers_proto_goTypes = nil
	file_proto_numbers_proto_depIdxs = nil
}
